name: Tag and publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  NEXUS_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  MAVEN_KEYID: ${{ secrets.SIGNING_KEY_ID }}
  MAVEN_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Tag
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} bash .github/tag.sh
    - name: Build and Publish
      run: |
        bash .github/publish.sh
